### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by ekimkael** [mystroken/genese#1]
No how to use isn't yet writen, can you please provide it?
I need something like your package for a work I might have in few days so it will be helpful to know how it works before the project start

**Comment by mystroken** [comment]
Thanks for your interest @iamKael

The project still need contributions to be totally ready for production.

Currently I’m focused on adding some features... docs are scheduled but it could take a while

**Comment by ekimkael** [comment]
Okay!
Hope you can release it soon
